// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	Followings string
	Posts      string
	Users      string
}{
	Followings: "followings",
	Posts:      "posts",
	Users:      "users",
}
